# Generated by Django 3.2 on 2021-04-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_num', models.IntegerField()),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_time', models.DateTimeField()),
                ('article_text', models.TextField()),
                ('category_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.category')),
            ],
        ),
    ]
