# Generated by Django 3.2 on 2021-04-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210423_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_text',
            new_name='text',
        ),
    ]
