# Generated by Django 3.2 on 2021-04-23 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_article_text_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='community.category'),
        ),
    ]
